name: Run Python Script
on:
  schedule:
    - cron: '*/5 * * * *'  # Svakih 5 minuta
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Ovo preuzima ceo repozitorijum, uključujući sent_ads.txt
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python main.py
      - name: Commit changes to sent_ads.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sent_ads.txt
          git commit -m "Automatski ažuriran sent_ads.txt"
          git push