name: Run Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Pokreće se svakih 5 minuta
  workflow_dispatch:  # Omogućava ručno pokretanje

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ili verzija Pythona koju koristite

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager beautifulsoup4

      - name: Run script
        run: python main.py  # Zamijenite "main.py" sa imenom vašeg Python fajla
